import type { SeedContext } from "./_shared/context";
import { seedIds } from "./_shared/ids";

export async function seedDispatchQuotes({ prisma }: SeedContext): Promise<void> {
  const now = new Date();
  const tenMinutesFromNow = new Date(now.getTime() + 10 * 60 * 1000);
  const fiveMinutesFromNow = new Date(now.getTime() + 5 * 60 * 1000);
  const fiveMinutesAgo = new Date(now.getTime() - 5 * 60 * 1000);
  const threeMinutesAgo = new Date(now.getTime() - 3 * 60 * 1000);
  const twoMinutesAgo = new Date(now.getTime() - 2 * 60 * 1000);
  const oneMinuteAgo = new Date(now.getTime() - 1 * 60 * 1000);
  const thirtySecondsAgo = new Date(now.getTime() - 30 * 1000);
  const tenSecondsAgo = new Date(now.getTime() - 10 * 1000);
  const oneMinuteFromNow = new Date(now.getTime() + 60 * 1000);

  await prisma.quotes.upsert({
    where: { id: seedIds.quotes.successCentroBacuri },
    update: {
      commerce_user_id: seedIds.users.commerceCentro,
      origin_bairro_id: seedIds.locality.centro,
      destination_bairro_id: seedIds.locality.bacuri,
      urgency: "padrao",
      requested_at_iso: fiveMinutesAgo,
      distance_m: 3559,
      duration_s: 288,
      eta_min: 5,
      zone: 4,
      base_zone_brl: "10.00",
      urgency_brl: "0.00",
      sunday_brl: "0.00",
      holiday_brl: "0.00",
      rain_brl: "0.00",
      peak_brl: "1.00",
      total_brl: "11.00",
      is_raining: false,
      climate_source: "openweather",
      climate_confidence: "high",
      distance_time_provider: "bairro_matrix",
      climate_provider: "openweather",
      fallback_used: false,
      distance_time_latency_ms: 19,
      climate_latency_ms: 240,
      success: true,
      error_code: null,
      error_message: null,
      expires_at: tenMinutesFromNow,
      created_at: fiveMinutesAgo,
    },
    create: {
      id: seedIds.quotes.successCentroBacuri,
      commerce_user_id: seedIds.users.commerceCentro,
      origin_bairro_id: seedIds.locality.centro,
      destination_bairro_id: seedIds.locality.bacuri,
      urgency: "padrao",
      requested_at_iso: fiveMinutesAgo,
      distance_m: 3559,
      duration_s: 288,
      eta_min: 5,
      zone: 4,
      base_zone_brl: "10.00",
      urgency_brl: "0.00",
      sunday_brl: "0.00",
      holiday_brl: "0.00",
      rain_brl: "0.00",
      peak_brl: "1.00",
      total_brl: "11.00",
      is_raining: false,
      climate_source: "openweather",
      climate_confidence: "high",
      distance_time_provider: "bairro_matrix",
      climate_provider: "openweather",
      fallback_used: false,
      distance_time_latency_ms: 19,
      climate_latency_ms: 240,
      success: true,
      error_code: null,
      error_message: null,
      expires_at: tenMinutesFromNow,
      created_at: fiveMinutesAgo,
    },
  });

  await prisma.quotes.upsert({
    where: { id: seedIds.quotes.failureCentroSaoJose },
    update: {
      commerce_user_id: seedIds.users.commerceCentro,
      origin_bairro_id: seedIds.locality.centro,
      destination_bairro_id: seedIds.locality.saoJose,
      urgency: "urgente",
      requested_at_iso: oneMinuteAgo,
      distance_m: null,
      duration_s: null,
      eta_min: null,
      zone: null,
      base_zone_brl: null,
      urgency_brl: null,
      sunday_brl: null,
      holiday_brl: null,
      rain_brl: null,
      peak_brl: null,
      total_brl: null,
      is_raining: true,
      climate_source: "openweather",
      climate_confidence: "medium",
      distance_time_provider: null,
      climate_provider: "openweather",
      fallback_used: true,
      distance_time_latency_ms: null,
      climate_latency_ms: 321,
      success: false,
      error_code: "DISTANCE_TIME_UNAVAILABLE",
      error_message: "Nao foi possivel obter distancia/tempo para o par solicitado.",
      expires_at: oneMinuteFromNow,
      created_at: oneMinuteAgo,
    },
    create: {
      id: seedIds.quotes.failureCentroSaoJose,
      commerce_user_id: seedIds.users.commerceCentro,
      origin_bairro_id: seedIds.locality.centro,
      destination_bairro_id: seedIds.locality.saoJose,
      urgency: "urgente",
      requested_at_iso: oneMinuteAgo,
      distance_m: null,
      duration_s: null,
      eta_min: null,
      zone: null,
      base_zone_brl: null,
      urgency_brl: null,
      sunday_brl: null,
      holiday_brl: null,
      rain_brl: null,
      peak_brl: null,
      total_brl: null,
      is_raining: true,
      climate_source: "openweather",
      climate_confidence: "medium",
      distance_time_provider: null,
      climate_provider: "openweather",
      fallback_used: true,
      distance_time_latency_ms: null,
      climate_latency_ms: 321,
      success: false,
      error_code: "DISTANCE_TIME_UNAVAILABLE",
      error_message: "Nao foi possivel obter distancia/tempo para o par solicitado.",
      expires_at: oneMinuteFromNow,
      created_at: oneMinuteAgo,
    },
  });

  await prisma.quote_provider_attempts.deleteMany({
    where: {
      quote_id: {
        in: [seedIds.quotes.successCentroBacuri, seedIds.quotes.failureCentroSaoJose],
      },
    },
  });

  await prisma.quote_provider_attempts.createMany({
    data: [
      {
        quote_id: seedIds.quotes.successCentroBacuri,
        domain_key: "distance_time",
        provider_id: "bairro_matrix",
        attempt_no: 1,
        success: true,
        latency_ms: 19,
        error_code: null,
        response_sample: {
          distance_m: 3559,
          duration_s: 288,
        },
        created_at: fiveMinutesAgo,
      },
      {
        quote_id: seedIds.quotes.successCentroBacuri,
        domain_key: "climate",
        provider_id: "openweather",
        attempt_no: 1,
        success: true,
        latency_ms: 240,
        error_code: null,
        response_sample: {
          is_raining: false,
          confidence: "high",
        },
        created_at: fiveMinutesAgo,
      },
      {
        quote_id: seedIds.quotes.failureCentroSaoJose,
        domain_key: "distance_time",
        provider_id: "bairro_matrix",
        attempt_no: 1,
        success: false,
        latency_ms: 34,
        error_code: "NO_ROUTE_DATA",
        response_sample: {
          message: "Pair not available in matrix",
        },
        created_at: oneMinuteAgo,
      },
      {
        quote_id: seedIds.quotes.failureCentroSaoJose,
        domain_key: "distance_time",
        provider_id: "openrouteservice",
        attempt_no: 2,
        success: false,
        latency_ms: 410,
        error_code: "PROVIDER_TIMEOUT",
        response_sample: {
          message: "timeout",
        },
        created_at: tenSecondsAgo,
      },
    ],
  });

  await prisma.orders.updateMany({
    where: { id: seedIds.orders.searchingRider },
    data: { quote_id: seedIds.quotes.successCentroBacuri, updated_at: now },
  });

  await prisma.dispatch_batches.upsert({
    where: { id: seedIds.dispatch.batches.searchingRiderBatch1 },
    update: {
      order_id: seedIds.orders.searchingRider,
      zone_label: "Zona 4",
      batch_number: 1,
      top_limit: 3,
      opened_at: fiveMinutesAgo,
      closed_at: null,
      winner_offer_id: null,
      created_at: fiveMinutesAgo,
    },
    create: {
      id: seedIds.dispatch.batches.searchingRiderBatch1,
      order_id: seedIds.orders.searchingRider,
      zone_label: "Zona 4",
      batch_number: 1,
      top_limit: 3,
      opened_at: fiveMinutesAgo,
      closed_at: null,
      winner_offer_id: null,
      created_at: fiveMinutesAgo,
    },
  });

  await prisma.dispatch_offers.upsert({
    where: { id: seedIds.dispatch.offers.searchingJoaoPending },
    update: {
      batch_id: seedIds.dispatch.batches.searchingRiderBatch1,
      order_id: seedIds.orders.searchingRider,
      rider_user_id: seedIds.users.riderJoao,
      position_in_queue: 1,
      offered_at: oneMinuteAgo,
      expires_at: tenMinutesFromNow,
      decision: "pending",
      decision_reason: null,
      decided_at: null,
      created_at: oneMinuteAgo,
    },
    create: {
      id: seedIds.dispatch.offers.searchingJoaoPending,
      batch_id: seedIds.dispatch.batches.searchingRiderBatch1,
      order_id: seedIds.orders.searchingRider,
      rider_user_id: seedIds.users.riderJoao,
      position_in_queue: 1,
      offered_at: oneMinuteAgo,
      expires_at: tenMinutesFromNow,
      decision: "pending",
      decision_reason: null,
      decided_at: null,
      created_at: oneMinuteAgo,
    },
  });

  await prisma.dispatch_offers.upsert({
    where: { id: seedIds.dispatch.offers.searchingMariaRejected },
    update: {
      batch_id: seedIds.dispatch.batches.searchingRiderBatch1,
      order_id: seedIds.orders.searchingRider,
      rider_user_id: seedIds.users.riderMaria,
      position_in_queue: 2,
      offered_at: oneMinuteAgo,
      expires_at: tenMinutesFromNow,
      decision: "rejected",
      decision_reason: "Rider recusou oferta na tela inicial.",
      decided_at: tenSecondsAgo,
      created_at: oneMinuteAgo,
    },
    create: {
      id: seedIds.dispatch.offers.searchingMariaRejected,
      batch_id: seedIds.dispatch.batches.searchingRiderBatch1,
      order_id: seedIds.orders.searchingRider,
      rider_user_id: seedIds.users.riderMaria,
      position_in_queue: 2,
      offered_at: oneMinuteAgo,
      expires_at: tenMinutesFromNow,
      decision: "rejected",
      decision_reason: "Rider recusou oferta na tela inicial.",
      decided_at: tenSecondsAgo,
      created_at: oneMinuteAgo,
    },
  });

  await prisma.dispatch_offers.upsert({
    where: { id: seedIds.dispatch.offers.searchingPedroExpired },
    update: {
      batch_id: seedIds.dispatch.batches.searchingRiderBatch1,
      order_id: seedIds.orders.searchingRider,
      rider_user_id: seedIds.users.riderPedro,
      position_in_queue: 3,
      offered_at: fiveMinutesAgo,
      expires_at: tenSecondsAgo,
      decision: "expired",
      decision_reason: "Sem resposta dentro da janela de oferta.",
      decided_at: tenSecondsAgo,
      created_at: fiveMinutesAgo,
    },
    create: {
      id: seedIds.dispatch.offers.searchingPedroExpired,
      batch_id: seedIds.dispatch.batches.searchingRiderBatch1,
      order_id: seedIds.orders.searchingRider,
      rider_user_id: seedIds.users.riderPedro,
      position_in_queue: 3,
      offered_at: fiveMinutesAgo,
      expires_at: tenSecondsAgo,
      decision: "expired",
      decision_reason: "Sem resposta dentro da janela de oferta.",
      decided_at: tenSecondsAgo,
      created_at: fiveMinutesAgo,
    },
  });

  await prisma.dispatch_batches.upsert({
    where: { id: seedIds.dispatch.batches.searchingRiderBatch2 },
    update: {
      order_id: seedIds.orders.searchingRider,
      zone_label: "Zona 4",
      batch_number: 2,
      top_limit: 3,
      opened_at: twoMinutesAgo,
      closed_at: null,
      winner_offer_id: null,
      created_at: twoMinutesAgo,
    },
    create: {
      id: seedIds.dispatch.batches.searchingRiderBatch2,
      order_id: seedIds.orders.searchingRider,
      zone_label: "Zona 4",
      batch_number: 2,
      top_limit: 3,
      opened_at: twoMinutesAgo,
      closed_at: null,
      winner_offer_id: null,
      created_at: twoMinutesAgo,
    },
  });

  await prisma.dispatch_offers.upsert({
    where: { id: seedIds.dispatch.offers.searchingJoaoNoResponse },
    update: {
      batch_id: seedIds.dispatch.batches.searchingRiderBatch2,
      order_id: seedIds.orders.searchingRider,
      rider_user_id: seedIds.users.riderJoao,
      position_in_queue: 1,
      offered_at: twoMinutesAgo,
      expires_at: thirtySecondsAgo,
      decision: "no_response",
      decision_reason: "Oferta visualizada sem interacao antes do timeout.",
      decided_at: thirtySecondsAgo,
      created_at: twoMinutesAgo,
    },
    create: {
      id: seedIds.dispatch.offers.searchingJoaoNoResponse,
      batch_id: seedIds.dispatch.batches.searchingRiderBatch2,
      order_id: seedIds.orders.searchingRider,
      rider_user_id: seedIds.users.riderJoao,
      position_in_queue: 1,
      offered_at: twoMinutesAgo,
      expires_at: thirtySecondsAgo,
      decision: "no_response",
      decision_reason: "Oferta visualizada sem interacao antes do timeout.",
      decided_at: thirtySecondsAgo,
      created_at: twoMinutesAgo,
    },
  });

  await prisma.dispatch_offers.upsert({
    where: { id: seedIds.dispatch.offers.searchingMariaPendingBatch2 },
    update: {
      batch_id: seedIds.dispatch.batches.searchingRiderBatch2,
      order_id: seedIds.orders.searchingRider,
      rider_user_id: seedIds.users.riderMaria,
      position_in_queue: 2,
      offered_at: oneMinuteAgo,
      expires_at: fiveMinutesFromNow,
      decision: "pending",
      decision_reason: null,
      decided_at: null,
      created_at: oneMinuteAgo,
    },
    create: {
      id: seedIds.dispatch.offers.searchingMariaPendingBatch2,
      batch_id: seedIds.dispatch.batches.searchingRiderBatch2,
      order_id: seedIds.orders.searchingRider,
      rider_user_id: seedIds.users.riderMaria,
      position_in_queue: 2,
      offered_at: oneMinuteAgo,
      expires_at: fiveMinutesFromNow,
      decision: "pending",
      decision_reason: null,
      decided_at: null,
      created_at: oneMinuteAgo,
    },
  });

  await prisma.dispatch_offers.upsert({
    where: { id: seedIds.dispatch.offers.searchingPedroRejectedBatch2 },
    update: {
      batch_id: seedIds.dispatch.batches.searchingRiderBatch2,
      order_id: seedIds.orders.searchingRider,
      rider_user_id: seedIds.users.riderPedro,
      position_in_queue: 3,
      offered_at: threeMinutesAgo,
      expires_at: oneMinuteAgo,
      decision: "rejected",
      decision_reason: "Rider indisponivel no momento da oferta.",
      decided_at: oneMinuteAgo,
      created_at: threeMinutesAgo,
    },
    create: {
      id: seedIds.dispatch.offers.searchingPedroRejectedBatch2,
      batch_id: seedIds.dispatch.batches.searchingRiderBatch2,
      order_id: seedIds.orders.searchingRider,
      rider_user_id: seedIds.users.riderPedro,
      position_in_queue: 3,
      offered_at: threeMinutesAgo,
      expires_at: oneMinuteAgo,
      decision: "rejected",
      decision_reason: "Rider indisponivel no momento da oferta.",
      decided_at: oneMinuteAgo,
      created_at: threeMinutesAgo,
    },
  });

  await prisma.dispatch_batches.upsert({
    where: { id: seedIds.dispatch.batches.toCustomerBatch1 },
    update: {
      order_id: seedIds.orders.toCustomer,
      zone_label: "Zona 4",
      batch_number: 1,
      top_limit: 1,
      opened_at: new Date("2026-02-14T10:02:00.000Z"),
      closed_at: new Date("2026-02-14T10:07:00.000Z"),
      winner_offer_id: null,
      created_at: new Date("2026-02-14T10:02:00.000Z"),
    },
    create: {
      id: seedIds.dispatch.batches.toCustomerBatch1,
      order_id: seedIds.orders.toCustomer,
      zone_label: "Zona 4",
      batch_number: 1,
      top_limit: 1,
      opened_at: new Date("2026-02-14T10:02:00.000Z"),
      closed_at: new Date("2026-02-14T10:07:00.000Z"),
      winner_offer_id: null,
      created_at: new Date("2026-02-14T10:02:00.000Z"),
    },
  });

  await prisma.dispatch_offers.upsert({
    where: { id: seedIds.dispatch.offers.toCustomerMariaAccepted },
    update: {
      batch_id: seedIds.dispatch.batches.toCustomerBatch1,
      order_id: seedIds.orders.toCustomer,
      rider_user_id: seedIds.users.riderMaria,
      position_in_queue: 1,
      offered_at: new Date("2026-02-14T10:05:00.000Z"),
      expires_at: new Date("2026-02-14T10:08:00.000Z"),
      decision: "accepted",
      decision_reason: null,
      decided_at: new Date("2026-02-14T10:07:00.000Z"),
      created_at: new Date("2026-02-14T10:05:00.000Z"),
    },
    create: {
      id: seedIds.dispatch.offers.toCustomerMariaAccepted,
      batch_id: seedIds.dispatch.batches.toCustomerBatch1,
      order_id: seedIds.orders.toCustomer,
      rider_user_id: seedIds.users.riderMaria,
      position_in_queue: 1,
      offered_at: new Date("2026-02-14T10:05:00.000Z"),
      expires_at: new Date("2026-02-14T10:08:00.000Z"),
      decision: "accepted",
      decision_reason: null,
      decided_at: new Date("2026-02-14T10:07:00.000Z"),
      created_at: new Date("2026-02-14T10:05:00.000Z"),
    },
  });

  await prisma.dispatch_batches.update({
    where: { id: seedIds.dispatch.batches.toCustomerBatch1 },
    data: {
      winner_offer_id: seedIds.dispatch.offers.toCustomerMariaAccepted,
    },
  });
}
